-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PROJECT_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLIENT_OWNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLIENT_MEMBER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'LEAD';
